- package:
  - name: radicle
  - section:
    - name: test:e2e
    - message:
      - name: Redundant build-depends entry
      - depends:
        # Library is not required, but executable
        - git-remote-ipfs
