- package:
  - name: radicle
  - section:
    - name: test:e2e
    - message:
      - name: Redundant build-depends entry
      - depends: git-remote-ipfs
- package:
  - name: radicle-lang
  - section:
    - name: test:spec
    - message:
      # BEGIN export all for ease of debugging
      - name: Weeds exported
      - module:
        - name: Radicle.Tests
        - identifier:
          - atom
          - int
          - kw
          - parseTest
          - prettyEither
          - runPureCode
          - stackTraceLines
          - vec
      # END
